/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as LoggedinImport } from './routes/_loggedin'
import { Route as IndexImport } from './routes/index'
import { Route as UiRefTest4Import } from './routes/ui-ref/test4'
import { Route as UiRefTest3Import } from './routes/ui-ref/test3'
import { Route as UiRefTest2Import } from './routes/ui-ref/test2'
import { Route as UiRefTestImport } from './routes/ui-ref/test'
import { Route as LoggedinDashboardImport } from './routes/_loggedin/dashboard'
import { Route as LoggedinSupportingServicesIndexImport } from './routes/_loggedin/supporting-services/index'
import { Route as LoggedinProductionDataIndexImport } from './routes/_loggedin/production-data/index'
import { Route as LoggedinPersonsIndexImport } from './routes/_loggedin/persons/index'
import { Route as LoggedinPaymentTransactionsIndexImport } from './routes/_loggedin/payment-transactions/index'
import { Route as LoggedinOrganisationConfigIndexImport } from './routes/_loggedin/organisation-config/index'
import { Route as LoggedinLotsIndexImport } from './routes/_loggedin/lots/index'
import { Route as LoggedinFieldTasksIndexImport } from './routes/_loggedin/field-tasks/index'
import { Route as LoggedinFarmsIndexImport } from './routes/_loggedin/farms/index'
import { Route as LoggedinSupportingServicesActivityIdImport } from './routes/_loggedin/supporting-services/$activityId'
import { Route as LoggedinPersonsPersonIdImport } from './routes/_loggedin/persons/$personId'
import { Route as LoggedinPaymentTransactionsPaymentIdImport } from './routes/_loggedin/payment-transactions/$paymentId'
import { Route as LoggedinLotsLotIdImport } from './routes/_loggedin/lots/$lotId'
import { Route as LoggedinFarmsEudrReportImport } from './routes/_loggedin/farms/eudr-report'
import { Route as LoggedinFarmsFarmIdImport } from './routes/_loggedin/farms/$farmId'
import { Route as LoggedinConfigurationsVesselsImport } from './routes/_loggedin/configurations/vessels'
import { Route as LoggedinConfigurationsUsersImport } from './routes/_loggedin/configurations/users'
import { Route as LoggedinConfigurationsServiceInputTypesImport } from './routes/_loggedin/configurations/service-input-types'
import { Route as LoggedinConfigurationsServiceCategoryTypesImport } from './routes/_loggedin/configurations/service-category-types'
import { Route as LoggedinConfigurationsServiceCategoriesImport } from './routes/_loggedin/configurations/service-categories'
import { Route as LoggedinConfigurationsServiceActivityTypesImport } from './routes/_loggedin/configurations/service-activity-types'
import { Route as LoggedinConfigurationsSeasonsImport } from './routes/_loggedin/configurations/seasons'
import { Route as LoggedinConfigurationsProductsImport } from './routes/_loggedin/configurations/products'
import { Route as LoggedinConfigurationsProductTypesImport } from './routes/_loggedin/configurations/product-types'
import { Route as LoggedinConfigurationsPricesImport } from './routes/_loggedin/configurations/prices'
import { Route as LoggedinConfigurationsOrganisationsImport } from './routes/_loggedin/configurations/organisations'
import { Route as LoggedinConfigurationsLocationsImport } from './routes/_loggedin/configurations/locations'
import { Route as LoggedinConfigurationsImportDataImport } from './routes/_loggedin/configurations/import-data'
import { Route as LoggedinConfigurationsFacilitiesImport } from './routes/_loggedin/configurations/facilities'
import { Route as LoggedinConfigurationsCropsImport } from './routes/_loggedin/configurations/crops'
import { Route as LoggedinConfigurationsCropVarietiesImport } from './routes/_loggedin/configurations/crop-varieties'
import { Route as LoggedinConfigurationsCertificationTypesImport } from './routes/_loggedin/configurations/certification-types'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LoggedinRoute = LoggedinImport.update({
  id: '/_loggedin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UiRefTest4Route = UiRefTest4Import.update({
  path: '/ui-ref/test4',
  getParentRoute: () => rootRoute,
} as any)

const UiRefTest3Route = UiRefTest3Import.update({
  path: '/ui-ref/test3',
  getParentRoute: () => rootRoute,
} as any)

const UiRefTest2Route = UiRefTest2Import.update({
  path: '/ui-ref/test2',
  getParentRoute: () => rootRoute,
} as any)

const UiRefTestRoute = UiRefTestImport.update({
  path: '/ui-ref/test',
  getParentRoute: () => rootRoute,
} as any)

const LoggedinDashboardRoute = LoggedinDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => LoggedinRoute,
} as any)

const LoggedinSupportingServicesIndexRoute =
  LoggedinSupportingServicesIndexImport.update({
    path: '/supporting-services/',
    getParentRoute: () => LoggedinRoute,
  } as any)

const LoggedinProductionDataIndexRoute =
  LoggedinProductionDataIndexImport.update({
    path: '/production-data/',
    getParentRoute: () => LoggedinRoute,
  } as any)

const LoggedinPersonsIndexRoute = LoggedinPersonsIndexImport.update({
  path: '/persons/',
  getParentRoute: () => LoggedinRoute,
} as any)

const LoggedinPaymentTransactionsIndexRoute =
  LoggedinPaymentTransactionsIndexImport.update({
    path: '/payment-transactions/',
    getParentRoute: () => LoggedinRoute,
  } as any)

const LoggedinOrganisationConfigIndexRoute =
  LoggedinOrganisationConfigIndexImport.update({
    path: '/organisation-config/',
    getParentRoute: () => LoggedinRoute,
  } as any)

const LoggedinLotsIndexRoute = LoggedinLotsIndexImport.update({
  path: '/lots/',
  getParentRoute: () => LoggedinRoute,
} as any)

const LoggedinFieldTasksIndexRoute = LoggedinFieldTasksIndexImport.update({
  path: '/field-tasks/',
  getParentRoute: () => LoggedinRoute,
} as any)

const LoggedinFarmsIndexRoute = LoggedinFarmsIndexImport.update({
  path: '/farms/',
  getParentRoute: () => LoggedinRoute,
} as any)

const LoggedinSupportingServicesActivityIdRoute =
  LoggedinSupportingServicesActivityIdImport.update({
    path: '/supporting-services/$activityId',
    getParentRoute: () => LoggedinRoute,
  } as any)

const LoggedinPersonsPersonIdRoute = LoggedinPersonsPersonIdImport.update({
  path: '/persons/$personId',
  getParentRoute: () => LoggedinRoute,
} as any)

const LoggedinPaymentTransactionsPaymentIdRoute =
  LoggedinPaymentTransactionsPaymentIdImport.update({
    path: '/payment-transactions/$paymentId',
    getParentRoute: () => LoggedinRoute,
  } as any)

const LoggedinLotsLotIdRoute = LoggedinLotsLotIdImport.update({
  path: '/lots/$lotId',
  getParentRoute: () => LoggedinRoute,
} as any)

const LoggedinFarmsEudrReportRoute = LoggedinFarmsEudrReportImport.update({
  path: '/farms/eudr-report',
  getParentRoute: () => LoggedinRoute,
} as any)

const LoggedinFarmsFarmIdRoute = LoggedinFarmsFarmIdImport.update({
  path: '/farms/$farmId',
  getParentRoute: () => LoggedinRoute,
} as any)

const LoggedinConfigurationsVesselsRoute =
  LoggedinConfigurationsVesselsImport.update({
    path: '/configurations/vessels',
    getParentRoute: () => LoggedinRoute,
  } as any)

const LoggedinConfigurationsUsersRoute =
  LoggedinConfigurationsUsersImport.update({
    path: '/configurations/users',
    getParentRoute: () => LoggedinRoute,
  } as any)

const LoggedinConfigurationsServiceInputTypesRoute =
  LoggedinConfigurationsServiceInputTypesImport.update({
    path: '/configurations/service-input-types',
    getParentRoute: () => LoggedinRoute,
  } as any)

const LoggedinConfigurationsServiceCategoryTypesRoute =
  LoggedinConfigurationsServiceCategoryTypesImport.update({
    path: '/configurations/service-category-types',
    getParentRoute: () => LoggedinRoute,
  } as any)

const LoggedinConfigurationsServiceCategoriesRoute =
  LoggedinConfigurationsServiceCategoriesImport.update({
    path: '/configurations/service-categories',
    getParentRoute: () => LoggedinRoute,
  } as any)

const LoggedinConfigurationsServiceActivityTypesRoute =
  LoggedinConfigurationsServiceActivityTypesImport.update({
    path: '/configurations/service-activity-types',
    getParentRoute: () => LoggedinRoute,
  } as any)

const LoggedinConfigurationsSeasonsRoute =
  LoggedinConfigurationsSeasonsImport.update({
    path: '/configurations/seasons',
    getParentRoute: () => LoggedinRoute,
  } as any)

const LoggedinConfigurationsProductsRoute =
  LoggedinConfigurationsProductsImport.update({
    path: '/configurations/products',
    getParentRoute: () => LoggedinRoute,
  } as any)

const LoggedinConfigurationsProductTypesRoute =
  LoggedinConfigurationsProductTypesImport.update({
    path: '/configurations/product-types',
    getParentRoute: () => LoggedinRoute,
  } as any)

const LoggedinConfigurationsPricesRoute =
  LoggedinConfigurationsPricesImport.update({
    path: '/configurations/prices',
    getParentRoute: () => LoggedinRoute,
  } as any)

const LoggedinConfigurationsOrganisationsRoute =
  LoggedinConfigurationsOrganisationsImport.update({
    path: '/configurations/organisations',
    getParentRoute: () => LoggedinRoute,
  } as any)

const LoggedinConfigurationsLocationsRoute =
  LoggedinConfigurationsLocationsImport.update({
    path: '/configurations/locations',
    getParentRoute: () => LoggedinRoute,
  } as any)

const LoggedinConfigurationsImportDataRoute =
  LoggedinConfigurationsImportDataImport.update({
    path: '/configurations/import-data',
    getParentRoute: () => LoggedinRoute,
  } as any)

const LoggedinConfigurationsFacilitiesRoute =
  LoggedinConfigurationsFacilitiesImport.update({
    path: '/configurations/facilities',
    getParentRoute: () => LoggedinRoute,
  } as any)

const LoggedinConfigurationsCropsRoute =
  LoggedinConfigurationsCropsImport.update({
    path: '/configurations/crops',
    getParentRoute: () => LoggedinRoute,
  } as any)

const LoggedinConfigurationsCropVarietiesRoute =
  LoggedinConfigurationsCropVarietiesImport.update({
    path: '/configurations/crop-varieties',
    getParentRoute: () => LoggedinRoute,
  } as any)

const LoggedinConfigurationsCertificationTypesRoute =
  LoggedinConfigurationsCertificationTypesImport.update({
    path: '/configurations/certification-types',
    getParentRoute: () => LoggedinRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_loggedin': {
      id: '/_loggedin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LoggedinImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_loggedin/dashboard': {
      id: '/_loggedin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LoggedinDashboardImport
      parentRoute: typeof LoggedinImport
    }
    '/ui-ref/test': {
      id: '/ui-ref/test'
      path: '/ui-ref/test'
      fullPath: '/ui-ref/test'
      preLoaderRoute: typeof UiRefTestImport
      parentRoute: typeof rootRoute
    }
    '/ui-ref/test2': {
      id: '/ui-ref/test2'
      path: '/ui-ref/test2'
      fullPath: '/ui-ref/test2'
      preLoaderRoute: typeof UiRefTest2Import
      parentRoute: typeof rootRoute
    }
    '/ui-ref/test3': {
      id: '/ui-ref/test3'
      path: '/ui-ref/test3'
      fullPath: '/ui-ref/test3'
      preLoaderRoute: typeof UiRefTest3Import
      parentRoute: typeof rootRoute
    }
    '/ui-ref/test4': {
      id: '/ui-ref/test4'
      path: '/ui-ref/test4'
      fullPath: '/ui-ref/test4'
      preLoaderRoute: typeof UiRefTest4Import
      parentRoute: typeof rootRoute
    }
    '/_loggedin/configurations/certification-types': {
      id: '/_loggedin/configurations/certification-types'
      path: '/configurations/certification-types'
      fullPath: '/configurations/certification-types'
      preLoaderRoute: typeof LoggedinConfigurationsCertificationTypesImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/configurations/crop-varieties': {
      id: '/_loggedin/configurations/crop-varieties'
      path: '/configurations/crop-varieties'
      fullPath: '/configurations/crop-varieties'
      preLoaderRoute: typeof LoggedinConfigurationsCropVarietiesImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/configurations/crops': {
      id: '/_loggedin/configurations/crops'
      path: '/configurations/crops'
      fullPath: '/configurations/crops'
      preLoaderRoute: typeof LoggedinConfigurationsCropsImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/configurations/facilities': {
      id: '/_loggedin/configurations/facilities'
      path: '/configurations/facilities'
      fullPath: '/configurations/facilities'
      preLoaderRoute: typeof LoggedinConfigurationsFacilitiesImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/configurations/import-data': {
      id: '/_loggedin/configurations/import-data'
      path: '/configurations/import-data'
      fullPath: '/configurations/import-data'
      preLoaderRoute: typeof LoggedinConfigurationsImportDataImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/configurations/locations': {
      id: '/_loggedin/configurations/locations'
      path: '/configurations/locations'
      fullPath: '/configurations/locations'
      preLoaderRoute: typeof LoggedinConfigurationsLocationsImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/configurations/organisations': {
      id: '/_loggedin/configurations/organisations'
      path: '/configurations/organisations'
      fullPath: '/configurations/organisations'
      preLoaderRoute: typeof LoggedinConfigurationsOrganisationsImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/configurations/prices': {
      id: '/_loggedin/configurations/prices'
      path: '/configurations/prices'
      fullPath: '/configurations/prices'
      preLoaderRoute: typeof LoggedinConfigurationsPricesImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/configurations/product-types': {
      id: '/_loggedin/configurations/product-types'
      path: '/configurations/product-types'
      fullPath: '/configurations/product-types'
      preLoaderRoute: typeof LoggedinConfigurationsProductTypesImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/configurations/products': {
      id: '/_loggedin/configurations/products'
      path: '/configurations/products'
      fullPath: '/configurations/products'
      preLoaderRoute: typeof LoggedinConfigurationsProductsImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/configurations/seasons': {
      id: '/_loggedin/configurations/seasons'
      path: '/configurations/seasons'
      fullPath: '/configurations/seasons'
      preLoaderRoute: typeof LoggedinConfigurationsSeasonsImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/configurations/service-activity-types': {
      id: '/_loggedin/configurations/service-activity-types'
      path: '/configurations/service-activity-types'
      fullPath: '/configurations/service-activity-types'
      preLoaderRoute: typeof LoggedinConfigurationsServiceActivityTypesImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/configurations/service-categories': {
      id: '/_loggedin/configurations/service-categories'
      path: '/configurations/service-categories'
      fullPath: '/configurations/service-categories'
      preLoaderRoute: typeof LoggedinConfigurationsServiceCategoriesImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/configurations/service-category-types': {
      id: '/_loggedin/configurations/service-category-types'
      path: '/configurations/service-category-types'
      fullPath: '/configurations/service-category-types'
      preLoaderRoute: typeof LoggedinConfigurationsServiceCategoryTypesImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/configurations/service-input-types': {
      id: '/_loggedin/configurations/service-input-types'
      path: '/configurations/service-input-types'
      fullPath: '/configurations/service-input-types'
      preLoaderRoute: typeof LoggedinConfigurationsServiceInputTypesImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/configurations/users': {
      id: '/_loggedin/configurations/users'
      path: '/configurations/users'
      fullPath: '/configurations/users'
      preLoaderRoute: typeof LoggedinConfigurationsUsersImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/configurations/vessels': {
      id: '/_loggedin/configurations/vessels'
      path: '/configurations/vessels'
      fullPath: '/configurations/vessels'
      preLoaderRoute: typeof LoggedinConfigurationsVesselsImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/farms/$farmId': {
      id: '/_loggedin/farms/$farmId'
      path: '/farms/$farmId'
      fullPath: '/farms/$farmId'
      preLoaderRoute: typeof LoggedinFarmsFarmIdImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/farms/eudr-report': {
      id: '/_loggedin/farms/eudr-report'
      path: '/farms/eudr-report'
      fullPath: '/farms/eudr-report'
      preLoaderRoute: typeof LoggedinFarmsEudrReportImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/lots/$lotId': {
      id: '/_loggedin/lots/$lotId'
      path: '/lots/$lotId'
      fullPath: '/lots/$lotId'
      preLoaderRoute: typeof LoggedinLotsLotIdImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/payment-transactions/$paymentId': {
      id: '/_loggedin/payment-transactions/$paymentId'
      path: '/payment-transactions/$paymentId'
      fullPath: '/payment-transactions/$paymentId'
      preLoaderRoute: typeof LoggedinPaymentTransactionsPaymentIdImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/persons/$personId': {
      id: '/_loggedin/persons/$personId'
      path: '/persons/$personId'
      fullPath: '/persons/$personId'
      preLoaderRoute: typeof LoggedinPersonsPersonIdImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/supporting-services/$activityId': {
      id: '/_loggedin/supporting-services/$activityId'
      path: '/supporting-services/$activityId'
      fullPath: '/supporting-services/$activityId'
      preLoaderRoute: typeof LoggedinSupportingServicesActivityIdImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/farms/': {
      id: '/_loggedin/farms/'
      path: '/farms'
      fullPath: '/farms'
      preLoaderRoute: typeof LoggedinFarmsIndexImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/field-tasks/': {
      id: '/_loggedin/field-tasks/'
      path: '/field-tasks'
      fullPath: '/field-tasks'
      preLoaderRoute: typeof LoggedinFieldTasksIndexImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/lots/': {
      id: '/_loggedin/lots/'
      path: '/lots'
      fullPath: '/lots'
      preLoaderRoute: typeof LoggedinLotsIndexImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/organisation-config/': {
      id: '/_loggedin/organisation-config/'
      path: '/organisation-config'
      fullPath: '/organisation-config'
      preLoaderRoute: typeof LoggedinOrganisationConfigIndexImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/payment-transactions/': {
      id: '/_loggedin/payment-transactions/'
      path: '/payment-transactions'
      fullPath: '/payment-transactions'
      preLoaderRoute: typeof LoggedinPaymentTransactionsIndexImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/persons/': {
      id: '/_loggedin/persons/'
      path: '/persons'
      fullPath: '/persons'
      preLoaderRoute: typeof LoggedinPersonsIndexImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/production-data/': {
      id: '/_loggedin/production-data/'
      path: '/production-data'
      fullPath: '/production-data'
      preLoaderRoute: typeof LoggedinProductionDataIndexImport
      parentRoute: typeof LoggedinImport
    }
    '/_loggedin/supporting-services/': {
      id: '/_loggedin/supporting-services/'
      path: '/supporting-services'
      fullPath: '/supporting-services'
      preLoaderRoute: typeof LoggedinSupportingServicesIndexImport
      parentRoute: typeof LoggedinImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LoggedinRoute: LoggedinRoute.addChildren({
    LoggedinDashboardRoute,
    LoggedinConfigurationsCertificationTypesRoute,
    LoggedinConfigurationsCropVarietiesRoute,
    LoggedinConfigurationsCropsRoute,
    LoggedinConfigurationsFacilitiesRoute,
    LoggedinConfigurationsImportDataRoute,
    LoggedinConfigurationsLocationsRoute,
    LoggedinConfigurationsOrganisationsRoute,
    LoggedinConfigurationsPricesRoute,
    LoggedinConfigurationsProductTypesRoute,
    LoggedinConfigurationsProductsRoute,
    LoggedinConfigurationsSeasonsRoute,
    LoggedinConfigurationsServiceActivityTypesRoute,
    LoggedinConfigurationsServiceCategoriesRoute,
    LoggedinConfigurationsServiceCategoryTypesRoute,
    LoggedinConfigurationsServiceInputTypesRoute,
    LoggedinConfigurationsUsersRoute,
    LoggedinConfigurationsVesselsRoute,
    LoggedinFarmsFarmIdRoute,
    LoggedinFarmsEudrReportRoute,
    LoggedinLotsLotIdRoute,
    LoggedinPaymentTransactionsPaymentIdRoute,
    LoggedinPersonsPersonIdRoute,
    LoggedinSupportingServicesActivityIdRoute,
    LoggedinFarmsIndexRoute,
    LoggedinFieldTasksIndexRoute,
    LoggedinLotsIndexRoute,
    LoggedinOrganisationConfigIndexRoute,
    LoggedinPaymentTransactionsIndexRoute,
    LoggedinPersonsIndexRoute,
    LoggedinProductionDataIndexRoute,
    LoggedinSupportingServicesIndexRoute,
  }),
  LoginRoute,
  UiRefTestRoute,
  UiRefTest2Route,
  UiRefTest3Route,
  UiRefTest4Route,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_loggedin",
        "/login",
        "/ui-ref/test",
        "/ui-ref/test2",
        "/ui-ref/test3",
        "/ui-ref/test4"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/_loggedin": {
      "filePath": "_loggedin.tsx",
      "children": [
        "/_loggedin/dashboard",
        "/_loggedin/configurations/certification-types",
        "/_loggedin/configurations/crop-varieties",
        "/_loggedin/configurations/crops",
        "/_loggedin/configurations/facilities",
        "/_loggedin/configurations/import-data",
        "/_loggedin/configurations/locations",
        "/_loggedin/configurations/organisations",
        "/_loggedin/configurations/prices",
        "/_loggedin/configurations/product-types",
        "/_loggedin/configurations/products",
        "/_loggedin/configurations/seasons",
        "/_loggedin/configurations/service-activity-types",
        "/_loggedin/configurations/service-categories",
        "/_loggedin/configurations/service-category-types",
        "/_loggedin/configurations/service-input-types",
        "/_loggedin/configurations/users",
        "/_loggedin/configurations/vessels",
        "/_loggedin/farms/$farmId",
        "/_loggedin/farms/eudr-report",
        "/_loggedin/lots/$lotId",
        "/_loggedin/payment-transactions/$paymentId",
        "/_loggedin/persons/$personId",
        "/_loggedin/supporting-services/$activityId",
        "/_loggedin/farms/",
        "/_loggedin/field-tasks/",
        "/_loggedin/lots/",
        "/_loggedin/organisation-config/",
        "/_loggedin/payment-transactions/",
        "/_loggedin/persons/",
        "/_loggedin/production-data/",
        "/_loggedin/supporting-services/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_loggedin/dashboard": {
      "filePath": "_loggedin/dashboard.tsx",
      "parent": "/_loggedin"
    },
    "/ui-ref/test": {
      "filePath": "ui-ref/test.tsx"
    },
    "/ui-ref/test2": {
      "filePath": "ui-ref/test2.tsx"
    },
    "/ui-ref/test3": {
      "filePath": "ui-ref/test3.tsx"
    },
    "/ui-ref/test4": {
      "filePath": "ui-ref/test4.tsx"
    },
    "/_loggedin/configurations/certification-types": {
      "filePath": "_loggedin/configurations/certification-types.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/configurations/crop-varieties": {
      "filePath": "_loggedin/configurations/crop-varieties.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/configurations/crops": {
      "filePath": "_loggedin/configurations/crops.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/configurations/facilities": {
      "filePath": "_loggedin/configurations/facilities.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/configurations/import-data": {
      "filePath": "_loggedin/configurations/import-data.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/configurations/locations": {
      "filePath": "_loggedin/configurations/locations.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/configurations/organisations": {
      "filePath": "_loggedin/configurations/organisations.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/configurations/prices": {
      "filePath": "_loggedin/configurations/prices.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/configurations/product-types": {
      "filePath": "_loggedin/configurations/product-types.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/configurations/products": {
      "filePath": "_loggedin/configurations/products.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/configurations/seasons": {
      "filePath": "_loggedin/configurations/seasons.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/configurations/service-activity-types": {
      "filePath": "_loggedin/configurations/service-activity-types.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/configurations/service-categories": {
      "filePath": "_loggedin/configurations/service-categories.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/configurations/service-category-types": {
      "filePath": "_loggedin/configurations/service-category-types.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/configurations/service-input-types": {
      "filePath": "_loggedin/configurations/service-input-types.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/configurations/users": {
      "filePath": "_loggedin/configurations/users.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/configurations/vessels": {
      "filePath": "_loggedin/configurations/vessels.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/farms/$farmId": {
      "filePath": "_loggedin/farms/$farmId.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/farms/eudr-report": {
      "filePath": "_loggedin/farms/eudr-report.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/lots/$lotId": {
      "filePath": "_loggedin/lots/$lotId.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/payment-transactions/$paymentId": {
      "filePath": "_loggedin/payment-transactions/$paymentId.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/persons/$personId": {
      "filePath": "_loggedin/persons/$personId.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/supporting-services/$activityId": {
      "filePath": "_loggedin/supporting-services/$activityId.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/farms/": {
      "filePath": "_loggedin/farms/index.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/field-tasks/": {
      "filePath": "_loggedin/field-tasks/index.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/lots/": {
      "filePath": "_loggedin/lots/index.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/organisation-config/": {
      "filePath": "_loggedin/organisation-config/index.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/payment-transactions/": {
      "filePath": "_loggedin/payment-transactions/index.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/persons/": {
      "filePath": "_loggedin/persons/index.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/production-data/": {
      "filePath": "_loggedin/production-data/index.tsx",
      "parent": "/_loggedin"
    },
    "/_loggedin/supporting-services/": {
      "filePath": "_loggedin/supporting-services/index.tsx",
      "parent": "/_loggedin"
    }
  }
}
ROUTE_MANIFEST_END */
