export type MhRawFarm = {
  ID: number;
  'Start time': number;
  'Completion time': number;
  Email: string;
  Name: string;
  'Farmer Name:': string;
  'Farmer Code:': string;
  Gender: string;
  'Names of those present during inspection:': string;
  'Scope of Certiifcation': string;
  'Date of Inspection': number;
  'GPS Longitude': string;
  'GPS Latitude': string;
  Altitude: string;
  'Productive Coffee Trees': string;
  'Non-productive Coffee Trees': string;
  'Total Coffee Trees': string;
  "Last Year's Harvest - Parchment": string;
  "Last Year's Harvest - Cherry": string;
  'Current Estimate': string;
  'Area Under Coffee': string;
  'Area Under other Crops': string;
  'Area Under conservation': string;
  'Total Farm Area': string;
  'Are coffee plots same as registered in previous visit ?': string;
  'Number of Coffee Plots': string;
  'Number of Conventional Plots': string;
  "Do children (under 18 years) work on farmer's farm ? If yes, suspend this farmer.": string;
  'Child Labor - Comments/Observations ': string;
  'Farmer is contracted and kept copy of contract': string;
  'Farmer Contract - Comments/Observations ': string;
  'Farmer keeps simple production records2': string;
  'Production records - Comments/Observations ': string;
  "There is no chemical field next to any of farmer's coffee field": string;
  "Chemical field next to farmer's coffee field - Comments/Observations": string;
  'If there is chemical field, is there a buffer zone ?': string;
  'Distance from coffee garden(in metres)': string;
  'Select all crops grown on the Coffee Plots': string;
  'Select all crops grown on the Conventional Plots': string;
  'Is there Attestation for the plots': string;
  'Sketch of all plots Organic and Conventional has been drawn': string;
  'Farmer has been trained on organic standards': string;
  'Number of trainings attended': string;
  'Date of last Training': number;
  'There is good Waste disposal measure': string;
  'All water source around the farm are protected': string;
  'Farmer does not practice parallel production': string;
  'There is enough shade in coffee fields(atleast 50% coverage)': string;
  'Soil has nutrients good for coffee production': string;
  'Farmer is putting efforts to control soil erosion': string;
  'Farmer does not use of synthetic fertilizers': string;
  'Manure preparation and application complaint': string;
  'Type of manure complies with the standard': string;
  'Quantity of manure applied per tree': string;
  'Manure Turning times': string;
  'Duration to maturity': string;
  'Manure Month of Application': string;
  'Type of manure applied': string;
  'Number of Cows': string;
  'Number of goats': string;
  'Number of birds': string;
  "Is this crop health better than last year's crop ?": string;
  'Fresh manure does not flow directly into the coffee field': string;
  'Farmer does not use treated seed as intercrop': string;
  'Farmer plants nitrogen fixing crops as intercrop': string;
  'Which nitrogen fixing crop is planted as intercrop': string;
  'Is there pest and disease infestation ?': string;
  'Rate of Pest and disease infestation': string;
  'Efforts to control pests and diseases': string;
  'Farmer does not use disallowed pesticides': string;
  'Pesticide Material used': string;
  'Use of mechanical methods': string;
  'Use of biological methods': string;
  'Use of cultural methods': string;
  'Efforts to minimise killing pollinators': string;
  'Farmer does not use GMOs': string;
  'Farmer does not use chemical': string;
  'Minimum weeding/slashing': string;
  'Open Weeding': string;
  'No burning to control weeds': string;
  'Farmer picks only red ripe cherries': string;
  'Farmer uses clean and complaint collection containers': string;
  'Farmer uses own pulper': string;
  'Pulper used is registered by the project': string;
  'Cherry skins are appropriately disposed off': string;
  'Farmer uses clean and complaint materials for fermentation': string;
  'Farmer does not discharge waste water into streams': string;
  'Drying facilities kept in a very hygienic condition': string;
  'Coffee store is well separated from conventional stores': string;
  'No evidence of any unapproved materials in coffee store': string;
  'Storage area is kept clean': string;
  'Chances of famer using nonorganic inputs on organic farm': string;
  'Chances of neighboring farm using chemicals': string;
  'Chances of farmer storing chemicals in organic stores': string;
  'Chances of farmer applying fresh manure in coffee': string;
  'Other risk of contamination specify below': string;
  'Measure taken to minimize risk': string;
  'Upload Scanned copy of the sketch map as a PDF here': string;

  'Field 1: Field Name': string;
  'Field 1: Area(acres)': string;
  'Field 1: GPS Latitude': string;
  'Field 1: GPS Longitude': string;
  'Field 1: GPS Altitude': string;
  'Field 1: Stumped Trees': string;
  'Field 1: Productive Trees': string;
  'Field 1: Yield Estimate': string;
  'Field 1: Number of Young trees': string;
  'Field 1: Shade Trees': string;

  'Field 2: Field Name': string;
  'Field 2: Area': string;
  'Field 2: GPS Latitude': string;
  'Field 2: GPS Longitude': string;
  'Field 2: GPS Altitude': string;

  'Field 3: Field Name': string;
  'Field 3: Area': string;
  'Field 3: GPS Latitude': string;
  'Field 3: GPS Longitude': string;
  'Field 3: GPS Altitude': string;

  'Field 4: Field Name': string;
  'Field 4: Area': string;
  'Field 4: GPS Latitude': string;
  'Field 4: GPS Longitude': string;
  'Field 4: GPS Altitude': string;

  'Field 2: Number of Young trees ': string;
  'Field 3: Number of Young trees ': string;
  'Field 2: Stumped Trees': string;
  'Field 3: Stumped Trees': string;
  'Field 2: Productive Trees': string;
  'Field 3: Productive Trees': string;
  'Field 2: Yield Estimate': string;
  'Field 3: Yield Estimate': string;
  'Field 2: Comments/Observations': string;
  'Field 3: Comments/Observations': string;
  'Field 2: Shade Trees': string;
  'Field 3: Shade Trees': string;
  'Was there a follow up for this farmer from last season findings?': string;
  '1. Criterion': string;
  '1. Deviations': string;
  '1. Proposed corrective actions': string;
  'Name of Internal Inspector': string;
  '1. Responsible Person': string;
  '1. Time of action': number;
  '1. Follow-up Time': number;
  Age: string;
  'Farmer Group Name': string;
  Zone: string;
  'Did farmer plant any new coffee seedlings ?': string;
  'Date of Farmer Contract': number;
  'Number of sheep': string;
  'Compliance of this visit': string;
  'Condition (corrective measures) or Explanation': string;
  'Name of Internal Inspector who did the follow up3': string;
  'Compliance this year': string;
  'Additional Comments': string;
  'Upload a scanned copy of the full inspection form here as a pdf file': string;
};
