export const EXTERNAL_SCHEDULER_URL = 'scheduler';
export const FARM_INSPECTION_URL = ':org/farmsinspection';

export const SQUARE_METER_TO_ACRES_MULTIPLIER = 0.000247105;
export const SQUARE_METER_TO_HECTARES_MULTIPLIER = 0.0001;
export const HECTARE_TO_SQUARE_METER_MULTIPLIRE = 10000;

export const HECATRES_TO_ACRES_MULTIPLIER =
  10000 * SQUARE_METER_TO_ACRES_MULTIPLIER;
