/**
 * Done from "LTC - Step 5 - FARMS - HMA -  orijin-dataimport" sheet
 * at https://docs.google.com/spreadsheets/d/149l8GG14PLRcuUpM6zt5uPCdsqnJb7EVW1YZ89DBJiY/edit#gid=1318562372
 */
export type FarmFromExcel = {
  mainContactPerson: string;
  name: string;
  idLabelShort: string;
  contactGender: string;
  contactLastName: string;
  contactFirstName: string;
  season: string;
  contactDob: Date;
  'Date of birth': number;
  'Date of birth_1': number;
  contactIdentificationNumberType: string;
  contactIdentificationNumber: string;
  contactMaritalStatus: string;
  contractDate: Date;
  'Contract date': number;
  'Contract date_1': number;
  'Household longitude': number; // 0.4754627;
  'Household latitude': number; // 33.4573372;
  location: string; // '0.4754627;33.4573372;;';
  acreage: number;
  areaTotal: number;
  areaTotalHA: number;
  yieldEstimateRaw: number;
  maxQuantityProcessedLimitRaw: number;
  parentLocationParentParentParent: string; // 'MYG';
  parentLocationParentParentParentName: string; // 'MAYUGE';
  parentLocationParentParent: string; // 'KRR';
  parentLocationParentParentName: string; // 'KITYERERA';
  parentLocationParentName: string; // 'WANDEGEYA';
  VILLAGE: string; // 'WANDEGEYA';
  parentLocationName: string; // 'WANDEGEYA';
  parentFacilityName: string; // 'KITYERERA';
  registrationDate: Date; // '2023-05-30T00:00:00';
  'Date of registration': number; // 45076; <- Excel date
  'Date of registration_1': number; // 45076;
  creationStatus: string; // 'DataImport';
  certificationStatus: string; // 'Certified';
};

export type LtcChatpowExportFarm = {
  mainContactPerson: string;
  name: string;
  contactLastName: string;
  contactFirstName: string;
  season: string;
  idLabelShort: string;
  contactGender: string;
  contactDob: string;
  'Date of birth': string;
  contactEducation: string;
  contactIdentificationNumberType: string;
  contactIdentificationNumber: string;
  email: string;
  contactMaritalStatus: string;
  phone: string;
  'Number of phone numbers': string;
  'hh members': string;
  contractDate: string;
  'Contract date': string;
  'Household longitude': string;
  'Household latitude': string;
  'Household altitude': string;
  location: string;
  'N of farms': string;
  'Ttl plots': string;
  acreage: string;
  areaTotal: string;
  areaTotalHA: string;
  yieldEstimateRaw: string;
  maxQuantityProcessedLimitRaw: string;
  'Total infrastructure acrage': string;
  'Total conservation acreage': string;
  'Number of main crops': string;
  'Number of minor crops': string;
  'Number of attached structures': string;
  'Number of attached certifications': string;
  'Number of trainings': string;
  'Training types': string;
  'Number of livestock': string;
  Livestock: string;
  'Main source of cooking': string;
  'Main source of lighting': string;
  'Main roof construction': string;
  'Main wall construction': string;
  Assets: string;
  parentLocationParentParentParent: string;
  parentLocationParentParent: string;
  parentLocationParent: string;
  VILLAGE: string;
  parentLocation: string;
  parentFacility: string;
  registrationDate: string;
  'Date of registration': string;
  'Farmer entry mode': string;
  Surveyor: string;
  lastInspectionDate: string;
  'Last inspection date': string;
  'Date of approval': string;
  'certificationStatus\r': string;
};
