export const growers_summary_mock_data = [
  {
    name: "Makali",
    code: "MKL",
    oldOrganic: 68,
    newFarmers: 26,
    inConversion: 5,
    sanctioned: 1,
    totalFarmers: 182,
    visitedOnce: 182,
    visitedTwice: "-",
    coffeePlotsPerFarmer: 548,
    organicAcreage: 266.24,
    totalAcreage: 416.03,
    nonProductiveCoffee: 10905,
    productiveCoffee: 225798,
    totalCoffeeTrees: 236703,
    organicParchmentYield: 76707,
    organicCherryYield: 383530,
    newFarmersParchmentYield: 18584,
    newFarmersCherryYield: 154865,
    sanctionedYield: 416.03,
    acresBelow1: 328,
    acres1To2: 95,
    acresAbove2: 90,
    totalAcres: 513,
    farmerGroupsMale: 107,
    farmerGroupsFemale: 74,
    farmerGroupsSchoolChurch: "-",
    totalFarmerGroups: 181,
    percentageWomen: "41%",
    registeredFarmers: 181,
    pulperOwners: "-",
    percentagePulperOwners: "-",
  },
  {
    name: "Buginyanya",
    code: "BGY",
    oldOrganic: 94,
    newFarmers: 35,
    inConversion: 7,
    sanctioned: 2,
    totalFarmers: 92,
    visitedOnce: 92,
    visitedTwice: "-",
    coffeePlotsPerFarmer: 273,
    organicAcreage: 76.17,
    totalAcreage: 150.96,
    nonProductiveCoffee: 1100,
    productiveCoffee: 71824,
    totalCoffeeTrees: 72924,
    organicParchmentYield: 25404,
    organicCherryYield: 203665,
    newFarmersParchmentYield: 10745,
    newFarmersCherryYield: 89845,
    sanctionedYield: 254,
    acresBelow1: 216,
    acres1To2: 45,
    acresAbove2: 0,
    totalAcres: 261,
    farmerGroupsMale: 58,
    farmerGroupsFemale: 30,
    farmerGroupsSchoolChurch: "-",
    totalFarmerGroups: 88,
    percentageWomen: "34%",
    registeredFarmers: 88,
    pulperOwners: "-",
    percentagePulperOwners: "-",
  },
];

export const summary_of_acrees_mock_data = [
  {
    name: "Makali",
    below1: 328,
    oneToTwo: 95,
    above2: 90,
    totalAcres: 513,
    acres: 416.03,
    averageAcreagePerFarmer: 0.81,
    maleFarmers: 107,
    femaleFarmers: 74,
    schoolChurchFarmers: "-",
    totalFarmers: 181,
    percentageWomen: "41%",
    registeredFarmers: 181,
    pulpers: "#ERROR!",
    percentagePulperOwners: "#ERROR!",
  },
  {
    name: "Buginyanya",
    below1: 216,
    oneToTwo: 32,
    above2: 13,
    totalAcres: 261,
    acres: "#ERROR!",
    averageAcreagePerFarmer: "#ERROR!",
    maleFarmers: 58,
    femaleFarmers: 30,
    schoolChurchFarmers: "-",
    totalFarmers: 88,
    percentageWomen: "34%",
    registeredFarmers: 88,
    pulpers: "#ERROR!",
    percentagePulperOwners: "#ERROR!",
  },
];
